### ISSUE TITLE
Podfile: Unsupported options `{:exclusive=>true}` for target `Cloudipsp_Example`

### ISSUE THREAD

**Issue by artemmihelson** [cloudipsp/ios-sdk#2]
Hi there,

I use Cocoapods v1.2.0.beta.1 and I got the following error when I run `pod install`:

> Unsupported options `{:exclusive=>true}` for target `Cloudipsp_Example`

As it suggests, I have removed that option and got rid of this error. Anyway, that wasn't last one. Afterwards I got another one:

> Specs satisfying the `Cloudipsp (from `../`), Cloudipsp` dependency were found, but they required a higher minimum deployment target.

So I had to put platform version to the Podfile (the same as it is in podspec).

Below is the Podfile that works fine:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'Cloudipsp_Example' do
  pod 'Cloudipsp', :path => '../'
end

target 'Cloudipsp_Tests' do
  pod 'Cloudipsp', :path => '../'
end
```

Could you please update your Podfile so others don't scared of errors.

**Comment by dNadiia** [comment]
Updated. v0.2.8
