### ISSUE TITLE
Не открывает веб вью при подтверждении

### ISSUE THREAD

**Issue by krunduev** [cloudipsp/ios-sdk#6]
Выдает 
-[WKWebView setNavigationDelegate:] must be used from main thread only
-[WKWebView loadHTMLString:baseURL:] must be used from main thread only

И не открывает веб вью

В коде

\- (void)confirm:(PSPayConfirmation *)confirmation {
    dispatch_async(dispatch_get_main_queue(), ^{
        self.hidden = NO;
    });
    if (confirmation == nil) {
        @throw [NSException exceptionWithName:@"NullPointerException" reason:@"confirmation should be not null" userInfo:nil];
    }
    self.confirmation = confirmation;
    **self.navigationDelegate = self;
    [self loadHTMLString:confirmation.htmlPageContent baseURL:[NSURL URLWithString:confirmation.url]];**
}

**Comment by vberegovoy** [comment]
Was fixed.
